// <auto-generated />
namespace Divinus.Infra.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class AjusteTamanhoSenha : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AjusteTamanhoSenha));
        
        string IMigrationMetadata.Id
        {
            get { return "201906260404323_AjusteTamanhoSenha"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
